export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODECT_LIST_SUCCESS = 'PRODECT_LIST_SUCCESS'
export const PRODECT_LIST_FAIL = 'PRODECT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODECT_DETAILS_SUCCESS = 'PRODECT_DETAILS_SUCCESS'
export const PRODECT_DETAILS_FAIL = 'PRODECT_DETAILS_FAIL'